import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Dash",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <body className={roboto.className}>
        <Link href="/" replace={true}>Home </Link>
        <Link href="/" replace={true}> DashBoard</Link>
        <h1>Dashboard</h1>
        <hr/>
          {children}
        <hr/>
        <h1>Dashboard</h1>
      </body>
    </div>
  );
}
